### ISSUE TITLE
MacOS Installation Fixes!!

### ISSUE THREAD

**Issue by bgoodwine** [kelpup/kelpup.github.io#16]
- [x] fix numbering
- [x] tell them not to click on the ISO when they download it
- [x] fix typo in the note: "set it" not "set as"
- [ ] put a red circle around the UNETBOOTIN application
- [x] tell them WHERE system preferences is: hit the apple at the top left, select system preferences
- [x] tell them to go to the general tab under security and privacy
- [x] tell them unetbootin asks for their password each time they open it, so if they quit unetbootin and plug in an important usb there's no risk unetbootin will overwrite it
- [x] do NOT select distro, select ISO image
- [x] hit okay to allow unetbootin to access your files so you can go find your iso 
- [x] go to ISO: it’s called kelpup62-x.x.iso (x.x being the version), probably in the downloads folder
- [x] hit open after selecting it
- [x] give example: USB should be called something like /dev/disk2s1 
- [x] good practice to unplug your other USBs if you have multiple options 
- [x] if it doesn’t show up, try plugging your USB in and quitting and restarting unetbootin. sometimes it doesn’t recognize things plugged in after it starts
- [x] after hitting okay, hit allow when a popup asks to access volumes on a usable volume 
- [x] note: it might take a while, because it's moving an entire operating system onto your usb 
- [x] once it's bootable, (a) close everything and restart (b) don't take out your USB (c) be careful! messing with dangerous things!!
- [ ] add photos to recovery mode 
- [x] click your language
- [x] don't click things on the next page: go to utilities at the top left, and go to system recover mode (? check video for wording)
- [x] check: No Security, Allow booting from external or removable media
- [x] Go to the apple icon on the top left, hit restart
- [x] While it’s restarting, hit the [option] key to bring up the dual boot menu
- [ ] insert picture for this restart option 
- [x] Pick the option that isn’t macos ! to start kelpup 
- [x] tell them to just hit hte power button and power off then hit power on like normal to restart macos :) 
- [x] tell them they can save their session if they want to

**Comment by simonrodrig** [comment]
I think for the MacOS installation guide, it might be a good idea to recommend them to use [BalenaEtcher](https://www.balena.io/etcher/) instead of UNetbootin. The interface is a lot simpler in my opinion, which is important to accomodate for beginners and newcomers to Linux. It's also cross platform, so you can recommend that they use it on Windows as well, if you want.

**Comment by bgoodwine** [comment]
i trued to use balena etcher but it did not work for puppy linux :( not really sure why...

thank you though :)

**Comment by bgoodwine** [comment]
decided not to include pictures
